apiVersion : v1
kind: Pod
metadata:
  name: my-web
  labels:
    env   : prod
    app   : main
    tier  : fronend
    owner : Yevgenii

spec:
  containers:
    - name  : container-apache
      image : yevgeniis/k8sphp:1.0.2
      ports :
        - containerPort: 80


