apiVersion : v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    env   : prod
    app   : main
    tier  : fronend
    owner : Yevgenii

spec:
  containers:
    - name  : web1
      image : yevgeniis/k8sphp:1.0.0
      ports :
        - containerPort: 80

    - name  : container-api
      image : tomcat:8.5.38
      ports :
        - containerPort: 8080